apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 850748373480.dkr.ecr.us-east-1.amazonaws.com/frontend:dae241606c5bd488f0f5b783087e8f685eed94b4
          ports:
            - containerPort: 3000
