apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 850748373480.dkr.ecr.us-east-1.amazonaws.com/backend:bb78e62cb37b7a44efc3247974aaf18144589ffd
          ports:
            - containerPort: 5000

