apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 891975886417.dkr.ecr.us-east-1.amazonaws.com/mp-backend:908132c641560403241524a9d26d821cd3b131e1
          ports:
            - containerPort: 3000
