apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 850748373480.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: ee6c7447c9e139caefa36d61fb49e4520709d4dd
