apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 850748373480.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: 1cdba40f6870659f8369617ce7b8bdab452797b8
