apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: backend
  newName: 850748373480.dkr.ecr.us-east-1.amazonaws.com/backend
  newTag: 702db30c64fc57462a5c9f5e1dba923ef9fffe3c
